### ISSUE TITLE
Installation : TimeSide "Erreur interne du serveur"

### ISSUE THREAD

**Issue by AnasGhrab** [Parisson/Telemeta#193]
Following the README installation, with a fresh installation (images and containers), I get the error "Erreur interne du serveur" on TimeSide readers : 

http://147.135.192.114:8050/

**Comment by thomasfillon** [comment]
Hi Anas,

Are you using the master branch of Telemeta ?

**Comment by AnasGhrab** [comment]
I made another branch from the master to store my config these docker-compose.yml modifications : 

```
db:
  image: mysql
  volumes:
    - ./scripts/:/srv/scripts
    - ./data/mysql/:/var/lib/mysql
  volumes_from:
    - data
  env_file:
    - env/prod.env
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

and because I have another process on the 80 port : 

```
nginx:
  image: nginx
  ports:
    - "8050:80"
```

**Comment by thomasfillon** [comment]
OK, I'm now able to reproduce the same error on Travis-CI : https://travis-ci.org/Parisson/Telemeta/builds/282141744

**Comment by thomasfillon** [comment]
It should be fixed now after git submodule update (for /lib/Timeside submodule).

**Comment by AnasGhrab** [comment]
I still have the same problem after a git pull to the master, a merge to my branch, even a delete of the containers..

**Comment by thomasfillon** [comment]
Did you also update git submodule after the git pull from Telemeta master branch ? 
`git submodule update` 
and check that Timeside (in lib/Timeside directory) is at commit 86f699cd61d

You may also need to pull the new parisson/timeside:latest docker image

**Comment by AnasGhrab** [comment]
```
commit 86f699cd61db2c0dc7fed61c4bb9f44ca3d8868f
Author: Thomas Fillon <thomasfillon@users.noreply.github.com>
Date:   Mon Oct 2 16:11:57 2017 +0200

    Restrict networkx version
```

```
anas@server-1:/srv/Telemeta/lib/TimeSide$ sudo docker pull parisson/timeside:latest
latest: Pulling from parisson/timeside
Digest: sha256:8ecfe6a37759ef0ed3645d43dafbcc5a624c7d4c2b4c8ae3bb452f1bedcc8013
Status: Image is up to date for parisson/timeside:latest
```

But nothing (http://147.135.192.114:8050/)... I have tried also by editing the port in lib/TimeSide/docker-compose.yml and the password in lib/TimeSide/env/prod.py to be the same as in Telemeta/env/prod.py (I never had to to that), but no result.

**Comment by thomasfillon** [comment]
To be sure of the state of your repositiory, what is the output of the `git submodule` command, please ?

**Comment by AnasGhrab** [comment]
```
anas@server-1:/srv/Telemeta$ sudo git submodule
 13ffdfdca0b81fab654d4f464c59c19852640ddb doc/themes/pelican-bootstrap3 (v1.0-306-g13ffdfd)
 86f699cd61db2c0dc7fed61c4bb9f44ca3d8868f lib/TimeSide (utils-1696-g86f699cd)
 e7fd56599e9e22eddf92c1063419fec6ab82e15e telemeta/locale (heads/master)
 c2a0f19625f44ab2c3050b7784382ac7eb6939b0 telemeta/pages (heads/master)
```

**Comment by thomasfillon** [comment]
Have you tried to rebuild the container : 

```
docker-compose rm
docker-compose build
```

**Comment by AnasGhrab** [comment]
Now it is ok. But I do not understand... I thought I have already deleted the containers.. Anyway.. Thanks !

**Comment by thomasfillon** [comment]
Ok fine.

I think it is related to some bad mounting of `lib/timeside` in the docker-compose file that we need to correct.
Only the Dockerfile build process take into account the right Timeside mounting point (in /srv/plugins).

Many thanks again for your feedback because the master branch was actually broken.

**Comment by thomasfillon** [comment]
65e3c797d1ba8 should fix docker composition Timeside plugin mounting 
Now lib/Timeside mounting should be dynamic and no more requires to rebuild the docker-composition each time.
